# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/Apps/UnrealEngine/LinuxUnrealEngine5.6.0

TARGETS = \
	SurvivalHorrorGame-Android-DebugGame  \
	SurvivalHorrorGame-Android-Development  \
	SurvivalHorrorGame-Android-Shipping  \
	SurvivalHorrorGame-Linux-DebugGame  \
	SurvivalHorrorGame-Linux-Development  \
	SurvivalHorrorGame-Linux-Shipping  \
	SurvivalHorrorGame-LinuxArm64-DebugGame  \
	SurvivalHorrorGame-LinuxArm64-Development  \
	SurvivalHorrorGame-LinuxArm64-Shipping  \
	SurvivalHorrorGame \
	SurvivalHorrorGameEditor-Linux-DebugGame  \
	SurvivalHorrorGameEditor-Linux-Development  \
	SurvivalHorrorGameEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend SurvivalHorrorGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug SurvivalHorrorGameEditor-Linux-Debug


SurvivalHorrorGame-Android-DebugGame:
	 $(BUILD) SurvivalHorrorGame Android DebugGame  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame-Android-Development:
	 $(BUILD) SurvivalHorrorGame Android Development  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame-Android-Shipping:
	 $(BUILD) SurvivalHorrorGame Android Shipping  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame-Linux-DebugGame:
	 $(BUILD) SurvivalHorrorGame Linux DebugGame  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame-Linux-Development:
	 $(BUILD) SurvivalHorrorGame Linux Development  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame-Linux-Shipping:
	 $(BUILD) SurvivalHorrorGame Linux Shipping  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame-LinuxArm64-DebugGame:
	 $(BUILD) SurvivalHorrorGame LinuxArm64 DebugGame  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame-LinuxArm64-Development:
	 $(BUILD) SurvivalHorrorGame LinuxArm64 Development  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame-LinuxArm64-Shipping:
	 $(BUILD) SurvivalHorrorGame LinuxArm64 Shipping  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGame: SurvivalHorrorGame-Linux-Development

SurvivalHorrorGameEditor-Linux-DebugGame:
	 $(BUILD) SurvivalHorrorGameEditor Linux DebugGame  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGameEditor-Linux-Development:
	 $(BUILD) SurvivalHorrorGameEditor Linux Development  -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" $(ARGS)

SurvivalHorrorGameEditor: SurvivalHorrorGameEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/mnt/Apps/UnrealEngineProjects/SurvivalHorrorGame5.6/SurvivalHorrorGame.uproject" -Game 

.PHONY: $(TARGETS)
